default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  host: localhost
  port: 5432

development:
 <<: *default
 database: retro_app_development

test:
 <<: *default
 database: retro_app_test

production:
 <<: *default
 database: retro_app_production 
