# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RetrospectivesController, # rubocop:disable Metrics/BlockLength
               type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Retrospective. As you add validations to Retrospective, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { 'title' => 'test', 'description' => 'test',
      'date' => DateTime.now.to_date }
  end

  let(:invalid_attributes) do
    { 'title' => 'test', 'description' => 'test', 'date' => nil }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetrospectivesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      Retrospective.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      retrospective = Retrospective.create! valid_attributes
      get :show, params: { id: retrospective.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      retrospective = Retrospective.create! valid_attributes
      get :edit, params: { id: retrospective.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Retrospective' do
        expect do
          post :create, params: { retrospective: valid_attributes },
                        session: valid_session
        end.to change(Retrospective, :count).by(1)
      end

      it 'redirects to the created retrospective' do
        post :create, params: { retrospective: valid_attributes },
                      session: valid_session
        expect(response).to redirect_to(Retrospective.last)
      end
    end

    context 'with invalid params' do
      it 'returns a success response (i.e. to display the \'new\' template)' do
        post :create, params: { retrospective: invalid_attributes },
                      session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do # rubocop:disable Metrics/BlockLength
    context 'with valid params' do
      let(:new_attributes) do
        { 'title' => 'test', 'description' => 'test',
          'date' => DateTime.now.to_date }
      end

      it 'updates the requested retrospective' do
        retrospective = Retrospective.create! valid_attributes
        put :update, params: { id: retrospective.to_param,
                               retrospective: new_attributes },
                     session: valid_session
        retrospective.reload
        assert_equal retrospective.title, new_attributes['title']
        assert_equal retrospective.description, new_attributes['description']
        assert_equal retrospective.date, new_attributes['date']
      end

      it 'redirects to the retrospective' do
        retrospective = Retrospective.create! valid_attributes
        put :update, params: { id: retrospective.to_param,
                               retrospective: valid_attributes },
                     session: valid_session
        expect(response).to redirect_to(retrospective)
      end
    end

    context 'with invalid params' do
      it 'returns a success response (i.e. to display the \'edit\' template)' do
        retrospective = Retrospective.create! valid_attributes
        put :update, params: { id: retrospective.to_param,
                               retrospective: invalid_attributes },
                     session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested retrospective' do
      retrospective = Retrospective.create! valid_attributes
      expect do
        delete :destroy, params: { id: retrospective.to_param },
                         session: valid_session
      end.to change(Retrospective, :count).by(-1)
    end

    it 'redirects to the retrospectives list' do
      retrospective = Retrospective.create! valid_attributes
      delete :destroy, params: { id: retrospective.to_param },
                       session: valid_session
      expect(response).to redirect_to(retrospectives_url)
    end
  end
end
